# Generated by Django 3.1.4 on 2022-12-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='needed_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='task_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(choices=[('Operations', 'Operations'), ('FOH', 'FOH'), ('Sales', 'Sales')], max_length=100),
        ),
    ]
