# Generated by Django 3.1.4 on 2023-01-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='organisation',
        ),
    ]
