# Generated by Django 3.1.4 on 2022-12-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20221231_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='staff_asigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.staff_member'),
        ),
    ]
